# Generated by Django 6.0 on 2025-12-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('ARTIST', 'Artist'), ('TRACK', 'Track'), ('ALBUM', 'Album')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='MusicAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('ARTIST', 'Artist'), ('TRACK', 'Track'), ('ALBUM', 'Album')], max_length=50)),
                ('action', models.CharField(choices=[('LIKE', 'Like'), ('SAVE', 'Save')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_actions', to='core.user')),
            ],
        ),
    ]
